// Importación de fuentes de Google y estilos globales
import { Inter } from "next/font/google";
import "./globals.css";

// Configuración de la fuente 'Inter' con el subconjunto 'latin'
const inter = Inter({ subsets: ["latin"] });

// Metadatos del documento
export const metadata = {
    title: "Prueba 1",
    description: "Generated by create next app",
};

// Componente principal de layout
export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={`${inter.className} overflow-auto`}>
                {children}
            </body>
        </html>
    );
}
